# Generated by Django 6.0.7 on 2026-07-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto/Equipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción General')),
                ('especificaciones', models.TextField(blank=True, help_text='Especificaciones técnicas (presión, caudal, dimensiones, etc.)', null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Base (MXN)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock / Inventario')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible para venta/cotización?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas_tecnicas/', verbose_name='Ficha Técnica (PDF)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto / Equipo',
                'verbose_name_plural': 'Productos y Equipos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
