# Generated by Django 6.0.7 on 2026-08-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador unico para JS, ej: 'Ecodren-17'", unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_equipo', models.CharField(choices=[('ecojet', 'Ecojet'), ('ecovac', 'Ecovac'), ('ecodren', 'Ecodren'), ('ecoclean', 'Ecoclean')], default='ecodren', max_length=20)),
                ('tagline', models.TextField(help_text='Descripcion corta del equipo')),
                ('capacidad', models.CharField(max_length=50)),
                ('presion', models.CharField(max_length=50)),
                ('recomendado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['-recomendado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='maquinaria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.maquinaria')),
            ],
            options={
                'verbose_name': 'Imagen de Maquinaria',
                'verbose_name_plural': 'Imágenes de Maquinaria',
                'ordering': ['orden'],
            },
        ),
    ]
