# Generated by Django 6.0.7 on 2026-08-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maquinaria_imagenmaquinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesorioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('maquinarias', models.ManyToManyField(blank=True, related_name='accesorios_disponibles', to='core.maquinaria')),
            ],
            options={
                'verbose_name': 'Accesorio Extra',
                'verbose_name_plural': 'Accesorios Extras',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especificacion', models.CharField(help_text='Ej. Fibra de vidrio o Aluminio / 80 GPM / Hidrahulico', max_length=255)),
                ('icono', models.CharField(default='fa-screwdriver-wrench', help_text='Clase FontAwesome, ej: fa-water', max_length=50)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='core.maquinaria')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
