# Generated by Django 6.0.7 on 2026-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesorioextra_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='peso',
            field=models.CharField(blank=True, default='19,500 Kg', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='succion',
            field=models.CharField(blank=True, default='Alto vacío', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='tipo_trabajo',
            field=models.CharField(blank=True, default='Industrial', max_length=50, null=True),
        ),
    ]
