# Generated by Django 6.0.7 on 2026-08-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maquinaria_peso_maquinaria_succion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Alto rendimiento', max_length=100)),
                ('descripcion', models.CharField(help_text='Ej: Tecnologia avanzada para máxima eficiencia.', max_length=255)),
                ('icono', models.CharField(default='fa-shield-halved', help_text='Clase FontAwesome, ej: fa-shield-halved, fa-droplet, fa-gear', max_length=50)),
                ('orden', models.PositiveBigIntegerField(default=0)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_destacados', to='core.maquinaria')),
            ],
            options={
                'verbose_name': 'Puntos Destacado',
                'verbose_name_plural': 'Puntos Destacados',
                'ordering': ['orden'],
            },
        ),
    ]
