# Generated by Django 6.0.7 on 2026-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_puntodestacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='ficha_tecnica_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ficha_tecnica/', verbose_name='Ficha Tecnica (PDF)'),
        ),
    ]
