# Generated by Django 6.0.7 on 2026-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maquinaria_ficha_tecnica_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción corta')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('noticia', 'Noticia / Artículo'), ('redes', 'Publicación de Comunidad')], default='noticia', max_length=20, verbose_name='Tipo de contenido')),
                ('etiqueta_badge', models.CharField(blank=True, help_text='Ej: 04:35 Min, 20 May 2024, Empresa, Destacado', max_length=50, null=True)),
                ('duracion_o_fecha', models.CharField(blank=True, help_text='Ej: 04:35 Min ó 15 de mayo, 2024', max_length=50, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='recursos_portadas/', verbose_name='Imagen de Portada')),
                ('url_destino', models.URLField(blank=True, help_text='URL externa (ej: YouTube, Facebook, LinkedIn)', null=True)),
                ('red_social', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('ninguna', 'Ninguna / Web')], default='ninguna', max_length=20, verbose_name='Red Social')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Es destacado / Card grande?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicación / Recurso',
                'verbose_name_plural': 'Publicaciones y Recursos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
