# Generated by Django 6.0.7 on 2026-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_publicacionrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('noticia', 'Noticia / Artículo'), ('redes', 'Publicación de Comunidad'), ('fichas-tecnicas', 'Ficha Técnica'), ('manuales', 'Manual de Operación'), ('catalogos', 'Catalogo de Productos ')], default='noticia', max_length=20, verbose_name='Tipo de contenido'),
        ),
    ]
