# Generated by Django 6.0.7 on 2026-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_publicacionrecurso_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('categoria', models.CharField(choices=[('ficha', 'Ficha Técnica'), ('manual', 'Manual de Operación'), ('catalogo', 'Catálogo de Producto')], max_length=20, verbose_name='Categoría de Documento')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción corta')),
                ('archivo_pdf', models.FileField(upload_to='documentos_tecnicos/', verbose_name='Archivo PDF')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo / Visible?')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Técnico / Guía',
                'verbose_name_plural': 'Documentos Técnicos y Guías',
                'ordering': ['categoria', '-actualizado_en'],
            },
        ),
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('noticia', 'Noticia / Artículo'), ('redes', 'Publicación de Comunidad')], default='noticia', max_length=20, verbose_name='Tipo de contenido'),
        ),
    ]
