# Generated by Django 6.0.7 on 2026-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentotecnico_alter_publicacionrecurso_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionImpartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo del curso impartido')),
                ('fecha', models.CharField(help_text='Ej: 12 May 2024', max_length=50, verbose_name='Fecha del evento')),
                ('ubicacion', models.CharField(help_text='Ej: Monterrey, N', max_length=100, verbose_name='Ubicacion / Ciudad')),
                ('participantes', models.PositiveBigIntegerField(default=30, verbose_name='Numero de participantes')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='capacitaciones_exp/', verbose_name='Foto del evento')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Visible?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capacitación Impartida (Experiencia)',
                'verbose_name_plural': 'Capacitaciones Impartidas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CursoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo del curso')),
                ('fecha_proxima', models.CharField(default='Proximamente', max_length=100, verbose_name='Fecha / Estado')),
                ('duracion', models.CharField(default='5 Horas', max_length=50, verbose_name='Duracion')),
                ('precio', models.DecimalField(decimal_places=2, default=3800.0, max_digits=10, verbose_name='Precio (MXN)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos_disponibles/', verbose_name='Miniatura del Curso')),
                ('cupos', models.PositiveBigIntegerField(default=15, verbose_name='Cupos Disponibles')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Disponible para inscripcion?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso Disponible',
                'verbose_name_plural': 'Cursos Disponibles',
                'ordering': ['-creado_en'],
            },
        ),
    ]
