# Generated by Django 6.0.7 on 2026-08-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_capacitacionimpartida_cursodisponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, verbose_name='No. Cotización (Ej: COT-2026-042)')),
                ('equipo_solicitado', models.CharField(max_length=255, verbose_name='Equipo Solicitado')),
                ('vigencia', models.CharField(default='30 Jul 2026', max_length=100, verbose_name='Vigencia')),
                ('asesor_asignado', models.CharField(default='Ing. Roberto Martínez', max_length=150, verbose_name='Asesor Técnico Asignado')),
                ('tipo_operacion', models.CharField(default='Soporte Comercial Directo', max_length=150, verbose_name='Tipo de Operación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización Guardada',
                'verbose_name_plural': 'Cotizaciones Guardadas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=150, verbose_name='Nombre de la Ubicacion / Sucursal')),
                ('calle_numero', models.CharField(max_length=200, verbose_name='Calle y Numero')),
                ('colonia', models.CharField(max_length=150, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Codigo Postal')),
                ('ciudad_estado', models.CharField(max_length=150, verbose_name='Ciudad y Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de Entrega',
                'verbose_name_plural': 'Direcciones de Entrega',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=50, unique=True, verbose_name='ID pedido (Ej: #EC-2026-9821)')),
                ('equipo_insumo', models.CharField(max_length=255, verbose_name='Equipos / Insumo Solicitado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total (MXN)')),
                ('estatus', models.CharField(choices=[('aduana', 'En Aduana / Puerto'), ('proceso', 'En preparación'), ('entregado', 'Liberado / Entregado'), ('cancelado', 'Cancelado')], default='proceso', max_length=20, verbose_name='Estatus de Despacho')),
                ('fecha_operacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Operación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Historial de Pedidos',
                'ordering': ['-fecha_operacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='Servicios Hidrahilicos del Centro', max_length=200, verbose_name='Razón Social')),
                ('telefono', models.CharField(default='+52 55 XXXX XXXX', max_length=30, verbose_name='Telefono Operativo')),
                ('direccion_principal', models.TextField(default='Av. Central #123, Col. Industrial, C.P. 12345, Ciudad de México', verbose_name='Dirección de Entrega Principal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresa',
            },
        ),
    ]
