# Generated by Django 6.0.7 on 2026-08-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cotizacionguardada_direccionentrega_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorioextra',
            options={'verbose_name': 'Accesorio Opcional', 'verbose_name_plural': 'Accesorios Opcionales'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Refacción', 'verbose_name_plural': 'Categorías de Refacciones'},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name': 'Equipamiento', 'verbose_name_plural': 'Equipamientos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Producto / Refacción', 'verbose_name_plural': 'Productos y Refacciones'},
        ),
        migrations.AlterModelOptions(
            name='puntodestacado',
            options={'ordering': ['orden'], 'verbose_name': 'Punto Destacado', 'verbose_name_plural': 'Puntos Destacados'},
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='capacidad_m3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Capacidad numérica (m³)'),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='presion_psi',
            field=models.PositiveIntegerField(default=0, verbose_name='Presión numérica (PSI)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='maquinarias_compatibles',
            field=models.ManyToManyField(blank=True, related_name='refacciones_compatibles', to='core.maquinaria', verbose_name='Maquinaria(s) Compatible(s)'),
        ),
        migrations.AlterField(
            model_name='capacitacionimpartida',
            name='fecha',
            field=models.CharField(help_text='Ej: 12 May 2026', max_length=50, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='capacitacionimpartida',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='capacitaciones_exp/', verbose_name='Foto del Evento'),
        ),
        migrations.AlterField(
            model_name='capacitacionimpartida',
            name='participantes',
            field=models.PositiveIntegerField(default=30, verbose_name='Número de Participantes'),
        ),
        migrations.AlterField(
            model_name='capacitacionimpartida',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Curso Impartido'),
        ),
        migrations.AlterField(
            model_name='capacitacionimpartida',
            name='ubicacion',
            field=models.CharField(help_text='Ej: Monterrey, NL', max_length=100, verbose_name='Ubicación / Ciudad'),
        ),
        migrations.AlterField(
            model_name='cotizacionguardada',
            name='numero_cotizacion',
            field=models.CharField(max_length=50, verbose_name='No. Cotización'),
        ),
        migrations.AlterField(
            model_name='cursodisponible',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Disponible para inscripción?'),
        ),
        migrations.AlterField(
            model_name='cursodisponible',
            name='cupos',
            field=models.PositiveIntegerField(default=15, verbose_name='Cupos Disponibles'),
        ),
        migrations.AlterField(
            model_name='cursodisponible',
            name='duracion',
            field=models.CharField(default='5 Horas', max_length=50, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='cursodisponible',
            name='fecha_proxima',
            field=models.CharField(default='Próximamente', max_length=100, verbose_name='Fecha / Estado'),
        ),
        migrations.AlterField(
            model_name='cursodisponible',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Curso'),
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='calle_numero',
            field=models.CharField(max_length=200, verbose_name='Calle y Número'),
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='nombre_sucursal',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Ubicación / Sucursal'),
        ),
        migrations.AlterField(
            model_name='documentotecnico',
            name='archivo_pdf',
            field=models.FileField(upload_to='documentos_tecnicos/', verbose_name='Archivo PDF Oficial'),
        ),
        migrations.AlterField(
            model_name='documentotecnico',
            name='categoria',
            field=models.CharField(choices=[('ficha', 'Ficha Técnica General'), ('manual', 'Manual de Operación'), ('catalogo', 'Catálogo de Producto')], max_length=20, verbose_name='Categoría de Documento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='especificacion',
            field=models.CharField(help_text='Ej. Fibra de vidrio o Aluminio / 80 GPM / Hidráulico', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='icono',
            field=models.CharField(default='fa-screwdriver-wrench', help_text='Clase FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo / Publicado?'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='capacidad',
            field=models.CharField(help_text='Ej: 17 m³', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='categoria_equipo',
            field=models.CharField(choices=[('ecojet', 'Ecojet — Equipos de Presión'), ('ecovac', 'Ecovac — Equipos de Vacío'), ('ecodren', 'Ecodren — Equipos Mixtos'), ('ecoclean', 'Ecoclean — Equipos de Vacío Seco')], default='ecodren', max_length=20, verbose_name='Línea / Marca'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='ficha_tecnica_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichas_tecnicas_equipos/', verbose_name='Ficha Técnica Oficial del Equipo (PDF)'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='presion',
            field=models.CharField(help_text='Ej: 3000 PSI', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='recomendado',
            field=models.BooleanField(default=False, verbose_name='¿Equipo Destacado?'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='slug',
            field=models.SlugField(help_text="Identificador único para URL/JS, ej: 'ecodren-17'", unique=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tagline',
            field=models.TextField(help_text='Descripción corta del equipo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='equipo_insumo',
            field=models.CharField(max_length=255, verbose_name='Equipo / Insumo Solicitado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('aduana', 'En Aduana / Puerto'), ('proceso', 'En Preparación'), ('entregado', 'Liberado / Entregado'), ('cancelado', 'Cancelado')], default='proceso', max_length=20, verbose_name='Estatus de Despacho'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='razon_social',
            field=models.CharField(default='Servicios Hidráulicos del Centro', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='telefono',
            field=models.CharField(default='+52 55 XXXX XXXX', max_length=30, verbose_name='Teléfono Operativo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Categoría de Refacción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas (presión soportada, caudal GPM, diámetro, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ficha_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='fichas_tecnicas_refacciones/', verbose_name='Ficha Técnica de Refacción (PDF)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto / Refacción'),
        ),
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='duracion_o_fecha',
            field=models.CharField(blank=True, help_text='Ej: 04:35 Min ó 15 de mayo, 2026', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='etiqueta_badge',
            field=models.CharField(blank=True, help_text='Ej: 04:35 Min, 20 May 2026, Empresa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('noticia', 'Noticia / Artículo'), ('redes', 'Publicación de Comunidad')], default='noticia', max_length=30, verbose_name='Tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='publicacionrecurso',
            name='url_destino',
            field=models.URLField(blank=True, help_text='URL externa (YouTube, Facebook, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='puntodestacado',
            name='descripcion',
            field=models.CharField(help_text='Ej: Tecnología avanzada para máxima eficiencia.', max_length=255),
        ),
        migrations.AlterField(
            model_name='puntodestacado',
            name='icono',
            field=models.CharField(default='fa-shield-halved', help_text='Clase FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='puntodestacado',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
