# Generated by Django 6.0.7 on 2026-08-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_accesorioextra_options_alter_categoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(blank=True, choices=[('Maquinaria completa', 'Maquinaria completa'), ('Refacciones específicas', 'Refacciones específicas'), ('Servicio técnico', 'Servicio técnico'), ('Otro', 'Otro')], max_length=60, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cotizacion',
                'verbose_name_plural': 'Solicitudes de Cotizaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
