# Generated by Django 6.0.7 on 2026-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_solicitudcotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('', 'Sin etiqueta'), ('nuevo', 'Nuevo'), ('oferta', 'Oferta'), ('destacado', 'Destacado')], default='', max_length=20, verbose_name='Etiqueta visual'),
        ),
    ]
