# Generated by Django 6.0.7 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_producto_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionrecurso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='publicacionrecurso',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='publicacionrecurso',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopsis / Descripción larga'),
        ),
    ]
