# Generated by Django 6.0.7 on 2026-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_publicacionrecurso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='tema_preferido',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10, verbose_name='Tema de interfaz preferido'),
        ),
    ]
