# Generated by Django 6.0.7 on 2026-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_perfilempresa_tema_preferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='idioma_panel',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Ingles')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='moneda_defecto',
            field=models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dolar Americano')], default='MXN', max_length=3),
        ),
    ]
