# Generated by Django 6.0.7 on 2026-09-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_perfilempresa_idioma_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='conekta_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Orden Conekta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito / Débito'), ('spei', 'Trasferencia Interbancaria (SPEI)'), ('oxxo', 'Efectivo en Oxxo')], default='tarjeta', max_length=30, verbose_name='Metodo de Pago'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Item al comprar')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario (MXN)')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_curso', to='core.cursodisponible', verbose_name='Curso Adquirido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido', verbose_name='Pedido Asociado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='core.producto', verbose_name='Producto / Refacción')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Item del Pedido',
            },
        ),
    ]
