# Generated by Django 6.0.7 on 2026-09-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pedido_conekta_order_id_pedido_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item del Pedido', 'verbose_name_plural': 'Items del Pedido'},
        ),
    ]
