# Generated by Django 6.0.7 on 2026-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_itempedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisponible',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha exacta para el calendario'),
        ),
    ]
