# Generated by Django 6.0.7 on 2026-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cursodisponible_fecha_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChasisOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cabina', models.CharField(choices=[('convencional', 'Cabina Convencional'), ('cab_over', 'Cab Over (Cabina Recortada)')], max_length=20)),
                ('marca', models.CharField(choices=[('international', 'International'), ('freightliner', 'Freightliner'), ('isuzu', 'Izusu'), ('sinotruk', 'Sinotruk')], max_length=30)),
                ('nombre', models.CharField(help_text='Ej. International MV Series / WorkStar', max_length=100)),
                ('libra_minimas', models.PositiveBigIntegerField(help_text='Capacidad mínima requerida en lbs (Ej: 33000)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ['Opcion de Chasis'],
                'verbose_name_plural': 'Opciones de Chasis',
                'ordering': ['tipo_cabina', 'marca'],
            },
        ),
    ]
